language: python
sudo: required
dist: trusty
git:
  depth: 5
cache: pip
matrix:
  include:
  - python: 2.7
  - python: 3.5
  - python: 3.6
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
- os: osx
    osx_image: xcode7.3
    language: generic
    sudo: required
  - os: osx
    osx_image: xcode8.3
    language: generic
    sudo: required
before_install:
- travis_retry travis/before_install_stage.sh
install:
- travis_retry travis/install_stage.sh
script:
- travis_retry travis/script_stage.sh
after_success:
- travis_retry travis/deploy_wheels.sh
notifications:
  email: false
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: jh9kPAxK+0CnYvLiqJrtsl+J3tcc/evZw20mveIaGf+THAtPUtlzDeqQUGVFkaanlYx+kTaDyPoqea/AIMH9tzk0Fit0dQkkI96z+iJIiKr9h2gpYgFqgq/EMhbP0icmF3q2orMcfl/oqvYjwn/GYRlpHpzR9B27QJlDnw3jUvd+hd/swocfl+LunNpgvs83qkgEYUu5dRstWrgbPPoaFuXBhr7Cjlu9CFZltKOAC/KFy19x8FH8i7dUvmYLhjrFEYYgJYe+i6SXe34Pwb3turcHCFMU/O4gFCglERI2wYrvD+69ECxbq7pRscudKUVe3yTolewmophJjeyB4Cdh9PDjKVOloKaka6WkhA7YT0jygtowRTQE/wLN5JR9eS7zY9Il0KGBkYk3LfFmeXV8EVf9SWdxD6EmcKa0ImYcwHmPQXyt2lxMVwC/FiyRBVnIxhZeFLa1YQFI0/Y+jcg4kG2jTGCYFFZvaoIaCtPCcqV856q9EMA+/BFQnupbiE3zSdvhKL/iuwkghaF8V5B39R9saHwDVKnExuMyQK95FboOwjm06SWOEIiMIu+NrW/uU+0HWaEDlqjilv/L8dh6Jx/Hb8Wm4/0Hi+y8zh68Qc2pkAhG9Nf7Tn/Y27MNg5X+SfOHGF+j5TMZeXa64acYOxm8xIl/kWc9DAcioCr9eWs=
  on:
    repo: limix/limix-legacy
env:
  global:
    secure: EV6xfCNZg+hc9rf+nbRuLHsD2mHu0TCFf2f4rV5ECvix7hRUdPP7r7w6DgfOEUAIGmMW+SEQ+DQb+fb2fAUeWCTBsfqS5rDs6I5AxA27Kzs6FHwlcrJ57m57hNFqnhedxhDeHgv5/m3i/Z+1LuBBa2F11EN+MsS3023xPh4wb9COgwf5S5B8XaF5zaUkQyU91Lvi0hAI2orGwYrvH0hxdPS3RIF0ak7C4USqPug+efM4uMfasQpevukEmZUnRExfDqpF72AuzciMGMbLjSZD+ZhWMDZGkEOJUX0fUv47bwdOPZ5Ys533IfqKfiBZBrlYJ/B0FNOff3L7Y59RC7XvW4MF8sRPmbnGpBTOXWDbhsg0R4J563M4ij/tKGO5XLp1JdTllNSsqzBI8J50DYSR3RvTwoTOEi4MnWe077FYDZWd8WBg066vrnmUFUKWX3o/1YZoKWImfp75S6fCFcoOMV9W3EFtnKtT1AAvxsHMQ6caz5Kpzgi07Rq3yrpST01TVjwbp5hawXEvzRU86fAllTXTpVjWpsFQvjFPoIF/unehqe6qJ65FLvl8ngHMlra8lFVdAb8U9sZd2UwPP3o2Ra8kX9+fCNSTHISvvTPeh4SthYg8zwzRFQ7SQH2LjQukDwyadHN6rYEr8Xj8KMz2fjcCeaBmh9oZ5aPNuOr3bLk=
