language: python
python: 3.6
env:
  global:
  - PKG_NAME=limix_legacy
  - CIBW_SKIP="cp34-* cp35-*"
  - CIBW_TEST_COMMAND="python -c \"import $PKG_NAME; import sys; sys.exit($PKG_NAME.test())\""
  - CIBW_BEFORE_BUILD="pip install --upgrade cython numpy scipy"
matrix:
  include:
  - sudo: required
    services:
    - docker
  - os: osx
    language: generic
    before_install:
    - brew update
    - brew outdated python || brew upgrade python
    - brew unlink python && brew link python
    - export PATH="/usr/local/opt/python/libexec/bin:$PATH"
    - hash -r
    - pip install --upgrade pip setuptools wheel
script:
- |
  if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
    sudo mkdir -p /usr/local/man
    sudo chown -R "${USER}:admin" /usr/local/man
  fi
- pip install --upgrade cython numpy scipy
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
- pip install cibuildwheel>=0.9.2
- cibuildwheel --output-dir wheelhouse
- |
  if [ "${TRAVIS_TAG:-}" != "" ]; then
    pip install twine
    python -m twine upload --skip-existing wheelhouse/*
  fi
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: cvaQTg/YZjs36omwKZkOkcARHBhrjdWH3jGWFD9WQxZxl4odKkYPyeITB4V2U9QA2JUBB2iklLY0QL4DAAiA124iH2wNaHjHIMGFzFA79Zc352V3KtevPdPvLZaRpY5N4jyazSQLL+Abg7pnMoAerWRUZi5+SYupeCpfdjrnJjiS6O1ISPY2lO+yqjxkgCKtGK4Vu+ccaF5XuAvcny8cNRr0lccIeLSOLcj4xRlukvCbzZ4kMQ2dTBCoG/SCIumEEQjRCRsEG3aYpXEnbhyE9ItOZDTBMZPwAojjibB7sgSsWaMOrg9P6fYENtxQQ0Wx9/eQpXV+qoUz7hpo63VOFYbDuKV6TxTGNnNhk1rbo9HV8SAtNf4WZAcl/0uKhUe8LLfqfMOimSfDnFp4XJe2csNMrzXhZOoUiiZlKkV2fgjf2/IJrSYFwNmWJg9hRKE09BdAFqBuXh+gqcGBDJd0XJhph0wM9ukBp4uHIhJK1cSrr0dP3xg5TPb10OnKxr0ULZ3hupXUc7l2Ff2RKf01xnR5xqMNoQzbnIlw4p3pu7N08JJ3h9hbCEaaCJ2L3K+X3rdDCni0LMHA/EpZlUQyfoI8VWkvyHPX2fx37xYHAWbf0keW7sdJzcqkXhfWAS4D3gN0sRmLDnDbysIWFMSwj1fchzFrBqbTnLtssQQR/IU=
  on:
    tags:       true
    repo:       limix/limix-legacy
    banch:      master
    python: 3.6
