language: python
sudo: required
dist: trusty
git:
  depth: 5
matrix:
  include:
  - python: 2.7
  - python: 3.5
  - python: 3.6
before_install:
- pip install Cython
- travis/install_pandoc.sh
script:
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1` -vvv;
- pushd /
- python -c "import sys; import limix_legacy; sys.exit(limix_legacy.test())"
- popd
notifications:
  email: false
